### ISSUE TITLE
Retifier for Opera - Crashing on notification

### ISSUE THREAD

**Issue by Kent1000** [mcrozz/Retifier#26]
Is this extension meant to cause the browser(opera latest version 64bit) to fully restart cause its rather annoying... but I like having the notifications -_-

Retifer Extension version : Version 1.2.1
Opera Version : 32.0.1948.25 
OS : Windows 10 64-bit (WoW64)

**Comment by mcrozz** [comment]
Is this happening when you open extension's window, or just randomly?

**Comment by Kent1000** [comment]
Happens whenever a streamer starts/ends their stream (mainly ending their stream does do it when it opens too tho just i dont notice it sometimes)

**Comment by mcrozz** [comment]
Thank you for reporting, I'll look up for this issue when I got free time from uni

**Comment by Kent1000** [comment]
Definitely happens when streamer goes online / offline always.

**Comment by mcrozz** [comment]
Cannot confirm this bug on Retifier 1.2.1 on Opera 32.0.1948.74, on Windows 10 x64.

I'll try to run stress test, maybe I'll got something
